---- Limpando as tabelas e reiniciando IDs
----TRUNCATE TABLE ATENDIMENTO RESTART IDENTITY CASCADE;
----TRUNCATE TABLE COMPRA RESTART IDENTITY CASCADE;
----TRUNCATE TABLE PRODUTO RESTART IDENTITY CASCADE;
----TRUNCATE TABLE FUNCIONARIO RESTART IDENTITY CASCADE;
----TRUNCATE TABLE CLIENTE RESTART IDENTITY CASCADE;
----TRUNCATE TABLE MERCADO RESTART IDENTITY CASCADE;
--
--
---- Adicionando Mercados
---- MERCADO INSERIDO COM @QUERY
--
---- Adicionando Clientes
--
---- Adicionando Funcionários
--
---- Adicionando Atendimentos
--
---- Adicionando Produtos
--
---- Adicionando Compras
--
---- Atualizando dados
--
--
--
--
--
---- Consultas avançadas
---
--
--
----
--
--
--
--
